### ISSUE TITLE
Saltbox Behind Reverse Proxy

### ISSUE THREAD

**Issue by SysSU** [saltyorg/Saltbox#153] opened 2023-07-02 18:36 UTC
---

**Describe the problem**
On my home server I have installed Saltbox as a VM. My home server already has a reverse proxy using [NginxProxyManager](https://github.com/NginxProxyManager/nginx-proxy-manager), and I only have one public IP. I want to be able to setup NginxProxyManager to proxy to my Saltbox VM.

Right now if I try to proxy to port 80 I get a "Too many redirects" error. And if I try to proxy to 443 I get a 421 response with a "Misdirected Request" message in the browser.

**Describe any solutions you think might work**
I'm probably way off, but I think my first blocker is that I can only access Saltbox domains through HTTPS, and the SSL cert is not even valid.

**Additional context**
None

**Comment by owine** [comment] 2023-07-02 18:40
Try configure it the other way - port forward to Saltbox and then setup manual traefik rules to reverse proxy to your other services

**Comment by saltydk** [comment] 2023-07-04 16:18
We should probably add some file provider docs bits in regards to Traefik.

**Comment by saltydk** [comment] 2023-11-16 15:53
As this is kind of a duplicate of https://github.com/saltyorg/Saltbox/issues/127 I am closing it.

**Closed by saltydk** 2023-11-16 15:53 UTC
