### ISSUE TITLE
Auto delete archived backups

### ISSUE THREAD

**Issue by L8onJones** [saltyorg/Saltbox#163] opened 2023-09-11 20:47 UTC
I like the idea of having a backup saved elsewhere (cloud etc), but as a new backup is stored every time it's run, it takes up a lot of storage and if you forget to delete the archives there is a risk of filling the storage. It would be great if you could set an option in the settings for how many archived backups you'd like to keep and all others are deleted on successful backup.

**Describe any solutions you think might work**
Add a backups_to_keep field in the backup_config file and delete any backups over that number

**Comment by owine** [comment] 2023-09-11 20:57
Implemented in https://github.com/saltyorg/Saltbox/commit/804ef4d36b1c9dbfe166d18a8cdbdd24f1a3e44f

Dupe of #147

**Closed by owine** 2023-09-11 20:57 UTC
